### ISSUE TITLE
fingers

### ISSUE THREAD

**Issue by nischelwitzer** [hybridgroup/cylon-leapmotion#12]
hi,

i have tried the example leap/ardrone http://cylonjs.com/documentation/examples/cylon/js/leap_ardrone/ and hand.s seems not to work with the current leap driver on windows.

after changing to:

 var fingers = 0;
      hand.pointables.forEach(function(pointable){
        if(pointable.extended) fingers ++;
      });

it worked.

best,
          alex

**Comment by edgarsilva** [comment]
Closing this issue since it's been a while and there is no follow up. Assume issue fixed.
