### ISSUE TITLE
Error: Could not find module "/app/node_modules/cylon-leapmotion/node_modules/lea/index.js"

### ISSUE THREAD

**Issue by cylinderStudio** [hybridgroup/cylon-leapmotion#15]
I'm attempting to write a Cylon robot that has a Tessel Board with a servo module, and a Leap Motion. With Tessel alone, my code was running fine, but after adding the Leap Motion and its Cylon library, I ran into trouble. When I run the new code on Tessel, here's the console log:

```
TESSEL! Connected to TM-00-04-f000da30-00614745-4ab565c2.
INFO Bundling directory /Users/studio/cylon/servo
INFO Deploying bundle (5.42 MB)...
INFO Running script...
I, [2015-02-15T05:58:26.632Z]  INFO -- : Initializing connections.
Error: Could not find module "/app/node_modules/cylon-leapmotion/node_modules/lea/index.js"
    at js_new ([string "colony-init.lua"]:1)
    at run ([string "colony-node.lua"]:1)
    at require ([string "colony-node.lua"]:1)
    at res (/app/node_modules/cylon-leapmotion/lib/adaptor.js:11)
    at run ([string "colony-node.lua"]:1)
    at require ([string "colony-node.lua"]:1)
    at res (/app/node_modules/cylon-leapmotion/lib/cylon-leapmotion.js:11)
    at run ([string "colony-node.lua"]:1)
    at require ([string "colony-node.lua"]:1)
    at <anonymous> (/app/node_modules/cylon/lib/registry.js:44)
```

And looking at the directory structure, that path would only resolve up to /lea/index.js because the /lea directory isn't there. At that point in the, it looks like it should go /leapjs/ but there's not an index.js file there, either.

Here are my dependencies:

```
"dependencies": {
  "cylon": "hybridgroup/cylon#tessel",
  "cylon-gpio": "~0.22.0",
  "cylon-i2c": "~0.19.0",
  "cylon-leapmotion": "^0.17.0",
  "cylon-tessel": "~0.10.0"
}
```

And if it's relevant, here are my connections and devices:

```
connections: {
  leapmotion: { adaptor: 'leapmotion' },
  tessel: { adaptor: 'tessel', port: 'A' }
},
devices: {
  leapmotion: { driver: 'leapmotion', connection: 'leapmotion' },
  servo: { driver: 'servo-pca9685', connection: 'tessel' }
}
```

**Comment by deadprogram** [comment]
Hi, @cylinderStudio the Leap Motion cannot currently be used with Tessel. 

The Leap Motion itself requires drivers to communicate with its host device, which is currently limited to OSX, Windows, and Linux using the Intel processor architecture, aka no Raspberry Pi support either.

Hope that helps!

**Comment by cylinderStudio** [comment]
Hiya, @deadprogram. Thanks for the response.

I guess I'm clueless about how Cylon works. I have another working app/Robot with a Leap Motion and the Arduino. I reckon the Leap isn't compatible with Arduino, but I don't get any errors there. Why is that?

**Comment by deadprogram** [comment]
@cylinderStudio yes, if you have your arduino hooked up to the computer via the USB interface, and you have the Leap Motion plugged in to your computer thru its cable, your computer is what is controlling everything.

**Comment by cylinderStudio** [comment]
OK, I think I got it now. I thought the Tessel was working in a similar way, but I understand now how it's different. Thanks for setting me straight!
